### Get auth token ### Admin Token: Authorization:  Basic VXNlcjE6UGFzc3dvcmQxIQ==
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "User1",
  "password": "Password1!"
}

### Positive test: Authorized user can create an account
POST http://localhost:4111/api/v1/accounts
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

### Negative test: Unauthorized user cannot create an account
POST http://localhost:4111/api/v1/accounts

### Positive test: Authorized user can see own accounts
GET http://localhost:4111/api/v1/customer/accounts
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

### Negative test: Unauthorized user cannot see accounts
POST http://localhost:4111/api/v1/accounts

### Positive test: Authorized user can deposit money to own account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "id": 1,
  "balance": 0.01
}

### Negative test: Unauthorized user cannot deposit money
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json

{
  "id": 1,
  "balance": 1
}

### Positive test: Authorized user can deposit maximum 5000
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "id": 1,
  "balance": 5000
}

### Negative test: Authorized user cannot deposit more than 5000
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "id": 1,
  "balance": 5000.01
}

### Negative test: Authorized user cannot deposit 0
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "id": 1,
  "balance": 0
}

### Negative test: Authorized user cannot deposit negative amount
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "id": 1,
  "balance": -0.01
}

### Negative test: Authorized user cannot deposit to nonexistent account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "id": 7514,
  "balance": 5000
}

### Negative test: Authorized user cannot deposit to another user's account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "id": 3,
  "balance": 1000
}




### Positive test: Authorized user can transfer money between own accounts
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 0.01
}

### Positive test: Authorized user can transfer money to another user account(maximum 10000)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 3,
  "amount": 10000
}

### Negative test: Unauthorized user cannot transfer money
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json

{
  "senderAccountId": 1,
  "receiverAccountId": 3,
  "amount": 10
}

### Negative test: Authorized user cannot transfer more than 10000
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 3,
  "amount": 10000.01
}

### Negative test: Authorized user cannot transfer 0
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 3,
  "amount": 0
}

### Negative test: Authorized user cannot transfer negative amount
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 3,
  "amount": -0.01
}

### Negative test: Authorized user cannot transfer more than sender balance
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "senderAccountId": 2,
  "receiverAccountId": 3,
  "amount": 10000
}

### Negative test: Authorized user cannot transfer from nonexisting account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "senderAccountId": 777,
  "receiverAccountId": 3,
  "amount": 10000
}

### Negative test: Authorized user cannot transfer to nonexisting account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 777,
  "amount": 100
}

### Negative test: Authorized user cannot transfer to the same account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 1,
  "amount": 100
}

### Negative test: Authorized user cannot transfer from not own account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "senderAccountId": 3,
  "receiverAccountId": 1,
  "amount": 100
}




### Positive test: Authorized user can see transactions of own accounts
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

### Negative test: Authorized user cannot see transactions of other users accounts
GET http://localhost:4111/api/v1/accounts/3/transactions
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

### Negative test: Unauthorized user cannot see transactions
GET http://localhost:4111/api/v1/accounts/3/transactions
Content-Type: application/json

### Negative test: Admin can not create an account
POST http://localhost:4111/api/v1/accounts
Authorization: Basic YWRtaW46YWRtaW4=




### Positive test: Authorized user can see own profile
GET http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

### Negative test: Unathorized user cannot see profile
GET http://localhost:4111/api/v1/customer/profile
Content-Type: application/json

### Positive test: Authorized user can change name on profile
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "name": "my newName"
}

### Negative test: Unauthorized user cannot change name on profile
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json

{
  "name": "My NewName"
}

### Negative test: Authorized user cannot change name to one word
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "name": "Name"
}

### Negative test: Authorized user cannot change name to three words
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "name": "My New Name"
}

### Negative test: Authorized user cannot change name with more than one space
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "name": "My  Name"
}

### Negative test: Authorized user cannot change name containing digits
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "name": "My  Name11"
}

### Negative test: Authorized user cannot change name containing special characters
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic VXNlcjE6UGFzc3dvcmQxIQ==

{
  "name": "My  Name%"
}